# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

<<<<<<< HEAD
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Cache .next build
        uses: actions/cache@v3
        with:
          path: .next
          key: ${{ runner.os }}-next-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next-build-

=======
<<<<<<< HEAD
    - name: Cache node_modules
<<<<<<< HEAD
      uses: actions/cache@v4
=======
      uses: actions/cache@v3
>>>>>>> c7d0e4c1772f9d8200882dfa935dbb389ef74b44
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Cache .next build
<<<<<<< HEAD
      uses: actions/cache@v4
=======
      uses: actions/cache@v3
>>>>>>> c7d0e4c1772f9d8200882dfa935dbb389ef74b44
      with:
        path: .next
        key: ${{ runner.os }}-next-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-next-build-
=======
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Cache .next build
        uses: actions/cache@v3
        with:
          path: .next
          key: ${{ runner.os }}-next-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next-build-
>>>>>>> 4368d2f6271663642adeede86071848316a5249f

>>>>>>> f0e5b50c4c2d1b451cdfb1cad276d439e6a5bf77
      - run: npm ci
      - run: npm run build
